//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proekt
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Класс уч.
    /// </summary>
    // *** Start programmer edit section *** (КлассУч CustomAttributes)

    // *** End programmer edit section *** (КлассУч CustomAttributes)
    [AutoAltered()]
    [Caption("Класс ученика")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КлассУчE", new string[] {
            "Назв as \'Название класса\'"})]
    [View("КлассУчL", new string[] {
            "Назв as \'Название класса\'"})]
    public class КлассУч : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазв;
        
        // *** Start programmer edit section *** (КлассУч CustomMembers)

        // *** End programmer edit section *** (КлассУч CustomMembers)

        
        /// <summary>
        /// Назв.
        /// </summary>
        // *** Start programmer edit section *** (КлассУч.Назв CustomAttributes)

        // *** End programmer edit section *** (КлассУч.Назв CustomAttributes)
        [StrLen(255)]
        public virtual string Назв
        {
            get
            {
                // *** Start programmer edit section *** (КлассУч.Назв Get start)

                // *** End programmer edit section *** (КлассУч.Назв Get start)
                string result = this.fНазв;
                // *** Start programmer edit section *** (КлассУч.Назв Get end)

                // *** End programmer edit section *** (КлассУч.Назв Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КлассУч.Назв Set start)

                // *** End programmer edit section *** (КлассУч.Назв Set start)
                this.fНазв = value;
                // *** Start programmer edit section *** (КлассУч.Назв Set end)

                // *** End programmer edit section *** (КлассУч.Назв Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КлассУчE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлассУчE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлассУчE", typeof(IIS.Proekt.КлассУч));
                }
            }
            
            /// <summary>
            /// "КлассУчL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлассУчL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлассУчL", typeof(IIS.Proekt.КлассУч));
                }
            }
        }
    }
}
