//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proekt
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Номер.
    /// </summary>
    // *** Start programmer edit section *** (Номер CustomAttributes)

    // *** End programmer edit section *** (Номер CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("НомерE", new string[] {
            "Наименование as \'Номер карты\'"})]
    [View("НомерL", new string[] {
            "Наименование as \'Номер карты\'"})]
    public class Номер : ICSSoft.STORMNET.DataObject
    {
        
        private int fНаименование;
        
        // *** Start programmer edit section *** (Номер CustomMembers)

        // *** End programmer edit section *** (Номер CustomMembers)

        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Номер.Наименование CustomAttributes)

        // *** End programmer edit section *** (Номер.Наименование CustomAttributes)
        public virtual int Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Номер.Наименование Get start)

                // *** End programmer edit section *** (Номер.Наименование Get start)
                int result = this.fНаименование;
                // *** Start programmer edit section *** (Номер.Наименование Get end)

                // *** End programmer edit section *** (Номер.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Номер.Наименование Set start)

                // *** End programmer edit section *** (Номер.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Номер.Наименование Set end)

                // *** End programmer edit section *** (Номер.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "НомерE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View НомерE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("НомерE", typeof(IIS.Proekt.Номер));
                }
            }
            
            /// <summary>
            /// "НомерL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View НомерL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("НомерL", typeof(IIS.Proekt.Номер));
                }
            }
        }
    }
}
