//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proekt
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Расписание.
    /// </summary>
    // *** Start programmer edit section *** (Расписание CustomAttributes)

    // *** End programmer edit section *** (Расписание CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РасписаниеE", new string[] {
            "Урок as \'Номер урока\'",
            "ПериодОт as \'Период От\'",
            "ПериодДо as \'Период До\'"})]
    [View("РасписаниеL", new string[] {
            "Урок as \'Номер урока\'",
            "ПериодОт as \'Период От\'",
            "ПериодДо as \'Период До\'"})]
    public class Расписание : ICSSoft.STORMNET.DataObject
    {
        
        private string fПериодОт;
        
        private string fПериодДо;
        
        private string fУрок;
        
        // *** Start programmer edit section *** (Расписание CustomMembers)

        // *** End programmer edit section *** (Расписание CustomMembers)

        
        /// <summary>
        /// ПериодДо.
        /// </summary>
        // *** Start programmer edit section *** (Расписание.ПериодДо CustomAttributes)

        // *** End programmer edit section *** (Расписание.ПериодДо CustomAttributes)
        [StrLen(255)]
        public virtual string ПериодДо
        {
            get
            {
                // *** Start programmer edit section *** (Расписание.ПериодДо Get start)

                // *** End programmer edit section *** (Расписание.ПериодДо Get start)
                string result = this.fПериодДо;
                // *** Start programmer edit section *** (Расписание.ПериодДо Get end)

                // *** End programmer edit section *** (Расписание.ПериодДо Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Расписание.ПериодДо Set start)

                // *** End programmer edit section *** (Расписание.ПериодДо Set start)
                this.fПериодДо = value;
                // *** Start programmer edit section *** (Расписание.ПериодДо Set end)

                // *** End programmer edit section *** (Расписание.ПериодДо Set end)
            }
        }
        
        /// <summary>
        /// ПериодОт.
        /// </summary>
        // *** Start programmer edit section *** (Расписание.ПериодОт CustomAttributes)

        // *** End programmer edit section *** (Расписание.ПериодОт CustomAttributes)
        [StrLen(255)]
        public virtual string ПериодОт
        {
            get
            {
                // *** Start programmer edit section *** (Расписание.ПериодОт Get start)

                // *** End programmer edit section *** (Расписание.ПериодОт Get start)
                string result = this.fПериодОт;
                // *** Start programmer edit section *** (Расписание.ПериодОт Get end)

                // *** End programmer edit section *** (Расписание.ПериодОт Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Расписание.ПериодОт Set start)

                // *** End programmer edit section *** (Расписание.ПериодОт Set start)
                this.fПериодОт = value;
                // *** Start programmer edit section *** (Расписание.ПериодОт Set end)

                // *** End programmer edit section *** (Расписание.ПериодОт Set end)
            }
        }
        
        /// <summary>
        /// Урок.
        /// </summary>
        // *** Start programmer edit section *** (Расписание.Урок CustomAttributes)

        // *** End programmer edit section *** (Расписание.Урок CustomAttributes)
        [StrLen(255)]
        public virtual string Урок
        {
            get
            {
                // *** Start programmer edit section *** (Расписание.Урок Get start)

                // *** End programmer edit section *** (Расписание.Урок Get start)
                string result = this.fУрок;
                // *** Start programmer edit section *** (Расписание.Урок Get end)

                // *** End programmer edit section *** (Расписание.Урок Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Расписание.Урок Set start)

                // *** End programmer edit section *** (Расписание.Урок Set start)
                this.fУрок = value;
                // *** Start programmer edit section *** (Расписание.Урок Set end)

                // *** End programmer edit section *** (Расписание.Урок Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "РасписаниеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РасписаниеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РасписаниеE", typeof(IIS.Proekt.Расписание));
                }
            }
            
            /// <summary>
            /// "РасписаниеL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РасписаниеL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РасписаниеL", typeof(IIS.Proekt.Расписание));
                }
            }
        }
    }
}
