//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proekt
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Статус ученика.
    /// </summary>
    // *** Start programmer edit section *** (Статус CustomAttributes)

    // *** End programmer edit section *** (Статус CustomAttributes)
    public enum Статус
    {
        
        // *** Start programmer edit section *** (Статус.Вход CustomAttributes)

        // *** End programmer edit section *** (Статус.Вход CustomAttributes)
        Вход,
        
        // *** Start programmer edit section *** (Статус.Выход CustomAttributes)

        // *** End programmer edit section *** (Статус.Выход CustomAttributes)
        Выход,
    }
}
